package com.xx_dev.apn.proxy.config;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/**
 * Created with IntelliJ IDEA.
 * User: xjx
 * Date: 13-10-15
 * Time: 下午10:45
 * To change this template use File | Settings | File Templates.
 */
public class ApnProxyPropertiesReader {

    public static void read(InputStream propertyFileInputStream) throws IOException {
        Properties properties = new Properties();
        properties.load(propertyFileInputStream);

        config(properties);
    }

    public static void read(File propertyFile) throws IOException {
        if (propertyFile.exists() && propertyFile.isFile()) {
            read(new FileInputStream(propertyFile));
        } else {
            Properties properties = new Properties();

            properties.put("apnproxy.pac_host", "localhost");

            properties.store(new FileOutputStream(propertyFile), "Generated by APN-PROXY");
        }
    }

    private static void config(Properties properties) {
        ApnProxyConfig.getConfig().setPacHost((String) properties.get("apnproxy.pac_host"));
    }
}
